-- AlterTable
ALTER TABLE "epochs" ADD COLUMN     "totalDeposits" DECIMAL(60,18) NOT NULL DEFAULT 0.0,
ADD COLUMN     "totalLocked" DECIMAL(60,18) NOT NULL DEFAULT 0.0,
ADD COLUMN     "totalUnlocked" DECIMAL(60,18) NOT NULL DEFAULT 0.0,
ADD COLUMN     "totalWithdrawals" DECIMAL(60,18) NOT NULL DEFAULT 0.0;

-- AlterTable
ALTER TABLE "member_epochs" ADD COLUMN     "userTotalDeposits" DECIMAL(60,18) NOT NULL DEFAULT 0.0,
ADD COLUMN     "userTotalLocked" DECIMAL(60,18) NOT NULL DEFAULT 0.0,
ADD COLUMN     "userTotalUnlocked" DECIMAL(60,18) NOT NULL DEFAULT 0.0,
ADD COLUMN     "userTotalWithdrawals" DECIMAL(60,18) NOT NULL DEFAULT 0.0,
ALTER COLUMN "isReleased" SET DEFAULT 0;
