groups:
  - name: api3tracker
    rules:
    - alert: BehindBlockchain
      expr: (downloaded_block_number - head_block_number) > 3500
      for: 0m
      labels:
        severity: warning
      annotations:
        summary: Downloading is delayed
        description: "Loading blocks is far behind head block {{ $value }}"

    - alert: ProcessingIsBehind
      expr: (processed_block_number - head_block_number) > 3500
      for: 0m
      labels:
        severity: warning
      annotations:
        summary: Processing is delayed
        description: "Processing blocks is far behind head block {{ $value }}"

    - alert: StatusBlocksNotDownloaded
      expr: blocks_without_status > 20
      for: 0m
      labels:
        severity: warning
      annotations:
        summary: Blocks without status update
        description: "Too many blocks without status update: {{ $value }}"

    - alert: StatusMembersNotDownloaded
      expr: address_without_status > 20
      for: 0m
      labels:
        severity: warning
      annotations:
        summary: Addresses without status update
        description: "Too many addresses without status update: {{ $value }}"

