groups:
  - name: api3tracker
    rules:
    - alert: BehindBlockchain
      expr: (downloaded_block_number - head_block_number) > 3500
      for: 0m
      labels:
        severity: warning
      annotations:
        summary: Downloading is delayed
        description: "Loading blocks is far behind head block {{ $value }}"

    - alert: ProcessingIsBehind
      expr: (processed_block_number - head_block_number) > 3500
      for: 0m
      labels:
        severity: warning
      annotations:
        summary: Processing is delayed
        description: "Processing blocks is far behind head block {{ $value }}"

    - alert: SharesBlocksNotDownloaded
      expr: blocks_without_shares > 20
      for: 0m
      labels:
        severity: warning
      annotations:
        summary: Blocks without shares update
        description: "Too many blocks without shares update: {{ $value }}"

    - alert: SharesMembersNotDownloaded
      expr: address_without_shares > 20
      for: 0m
      labels:
        severity: warning
      annotations:
        summary: Addresses without shares update
        description: "Too many addresses without shares update: {{ $value }}"

