groups:
  - name: blackbox-exporter
    rules:
    - alert: ProbeFailed
      expr: probe_success == 0
      for: 5m
      labels:
        severity: error
      annotations:
        summary: "Probe failed ({{ $labels.instance }})"
        description: "Probe failed STATUS = {{ $value }}"
    - alert: SlowProbe
      expr: avg_over_time(probe_duration_seconds[1m]) > 5
      for: 5m
      labels:
        severity: warning
      annotations:
        summary: "Slow probe ({{ $labels.instance }})"
        description: "Blackbox probe took more than 5s to complete\n TIME: {{ $value }}s"
    - alert: HttpStatusCode
      expr: probe_http_status_code <= 199 OR probe_http_status_code >= 400
      for: 5m
      labels:
        severity: error
      annotations:
        summary: "HTTP Status Code ({{ $labels.instance }})"
        description: "HTTP status code is not 200-399\nSTATUS: {{ $value }}"
    - alert: SslCertificateWillExpireSoon
      expr: probe_ssl_earliest_cert_expiry - time() < 86400 * 14
      for: 5m
      labels:
        severity: warning
      annotations:
        summary: "SSL certificate will expire soon ({{ $labels.instance }})"
        description: "SSL certificate expires in 14 days\nTIME: {{ $value }}"
    - alert: SslCertificateHasExpired
      expr: probe_ssl_earliest_cert_expiry - time()  <= 0
      for: 5m
      labels:
        severity: error
      annotations:
        summary: "SSL certificate has expired ({{ $labels.instance }})"
        description: "SSL certificate has expired already\nTIME: {{ $value }}"
    - alert: HttpSlowRequests
      expr: avg_over_time(probe_http_duration_seconds[1m]) > 5
      for: 5m
      labels:
        severity: warning
      annotations:
        summary: "HTTP slow requests ({{ $labels.instance }})"
        description: "HTTP request took more than 5s\nTIME: {{ $value }}"
