name: Docker Image CI

on:
  push:
    branches: [ "main", "i/**", "f/**" ]
  pull_request:
    branches: [ "main", "i/**", "f/**", "dependabot/**" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag api3tracker:$(date +%s)
    - name: Build the Storybook Docker image
      run: docker build . --file .storybook/Dockerfile --tag api3tracker-storybook:$(date +%s)
